# nixpacks.toml - Railway deployment configuration

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"

[variables]
PYTHONPATH = "/app"

